monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-Focusrite.*"
      }
      {
        node.name = "~alsa_(input|output).usb-Focusrite.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        api.alsa.headroom = 128
      }
    }
  }
]
